spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthsystem?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qpzja528

  jpa:
    hibernate:
      ddl-auto: create